### ISSUE TITLE
svd cuda error

### ISSUE THREAD

**Issue by liujianzhao6328057** [thuml/Domain-Adaptation-Regression#1]
When i use RSD loss, the following error will occur:

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
Traceback (most recent call last):
  File "train_SVD.py", line 274, in <module>
    main(args)
  File "train_SVD.py", line 118, in main
    rsd_loss = RSD(f_s,f_t)
  File "train_SVD.py", line 29, in RSD
    u_s, s_s, v_s = torch.svd(Feature_s.t())
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 18)

**Comment by chenxinyang123** [comment]
> When i use RSD loss, the following error will occur:
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> Traceback (most recent call last):
> File "train_SVD.py", line 274, in
> main(args)
> File "train_SVD.py", line 118, in main
> rsd_loss = RSD(f_s,f_t)
> File "train_SVD.py", line 29, in RSD
> u_s, s_s, v_s = torch.svd(Feature_s.t())
> RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 18)

Some versions of PyTorch may not work well using SVD. You can check your environment.
For me, I use Pytorch==0.4.1 and torchvision==0.2.1.

**Comment by jiusigua** [comment]
@chenxinyang123   你好，我在运行rsd算法时遇到同样的错，我尝试的pytorch版本有1.10、1.7、0.4.1均报同样的错，请问现在有新的解决办法吗？

**Comment by chenxinyang123** [comment]
@jiusigua 您好，我当时的实验中是没有出现这个问题的，即本库的代码在本库的环境下运行不会报错，这里我给出本库的环境列表，另外，我最近也在更多环境下尝试解决不同版本造成的问题，有结论了会告知您。

附：本库代码正常运行的环境
_libgcc_mutex             0.1                        main
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ca-certificates           2021.7.5             h06a4308_1
certifi                   2021.5.30        py37h06a4308_0
cffi                      1.14.6           py37h400218f_0
cuda92                    1.0                           0    pytorch
cudatoolkit               8.0                           3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
cudnn                     7.1.3                 cuda8.0_0
cycler                    0.10.0                   py37_0
dbus                      1.13.18              hb2f20db_0
expat                     2.4.1                h2531618_2
fontconfig                2.13.1               h6c09931_0
freetype                  2.10.4               h5ab3b9f_0
giflib                    5.2.1                h7b6447c_0
glib                      2.69.1               h5202010_0
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
h5py                      2.7.0               np113py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
hdf5                      1.8.17                        2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
icu                       58.2                 he6710b0_3
intel-openmp              2019.0                      118
jbig                      2.1                           0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9b                            0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
kiwisolver                1.3.1            py37h2531618_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.35.1               h7274673_9
libffi                    3.3                  he6710b0_2
libgcc                    5.2.0                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran               3.0.0                         1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.14                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
libopenblas               0.3.3                h5a2b251_3
libpng                    1.6.37               hbc83047_0
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.2.0                h85742a9_0
libuuid                   1.0.3                h1bed415_2
libwebp                   1.2.0                h89dd481_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
lz4-c                     1.9.3                h295c915_1
matplotlib                3.3.4            py37h06a4308_0
matplotlib-base           3.3.4            py37h62a2d02_0
mkl                       2020.2                      256
mkl-service               2.3.0            py37he8ac12f_0
mkl_fft                   1.0.10           py37ha843d7b_0
mkl_random                1.0.2            py37hd81dba3_0
nccl                      1.3.4                 cuda8.0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
ncurses                   6.2                  he6710b0_1
ninja                     1.7.2                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
numpy                     1.19.2           py37h54aff64_0
numpy-base                1.19.2           py37hfa32c7d_0
olefile                   0.46               pyhd3eb1b0_0
openblas                  0.2.19                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
openssl                   1.1.1l               h7f8727e_0
pcre                      8.45                 h295c915_0
pillow                    8.3.1            py37h5aabda8_0
pip                       21.2.2           py37h06a4308_0
pycparser                 2.20                       py_2
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py37h05f1152_2
python                    3.7.11               h12debd9_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytorch                   0.4.1           py37_cuda9.2.148_cudnn7.1.4_1  [cuda92]  pytorch
pytz                      2021.1             pyhd3eb1b0_0
qt                        5.9.7                h5867ecd_1
readline                  8.1                  h27cfd23_0
scikit-learn              0.24.2           py37ha9443f7_0
scipy                     1.6.2            py37h91f5cce_0
setuptools                58.0.4           py37h06a4308_0
sip                       4.19.8           py37hf484d3e_0
six                       1.16.0             pyhd3eb1b0_0
sqlite                    3.36.0               hc218d9a_0
threadpoolctl             2.2.0              pyh0d69192_0
tk                        8.6.11               h1ccaba5_0
torchvision               0.2.1                    py37_0
tornado                   6.1              py37h27cfd23_0
tqdm                      4.62.2             pyhd3eb1b0_1
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h7b6447c_0
yaml                      0.1.6                         0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zlib                      1.2.11                        0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
zstd                      1.4.9                haebb681_0

**Comment by jiusigua** [comment]
@chenxinyang123  非常感谢。顺便再向您详细描述一下遇到的问题：该问题不是一开始训练就报错，而是在训练二三十个epoch后，rsd_loss大概降到了3左右，然后在某个迭代中梯度里出现了大面积的nan和inf，所以导致更新的权重也变为了nan，网络正向计算得到的特征也就全部变为nan，最后传入到计算rsd loss的函数中，svd计算就报上述的错误。本人猜测是否在rsd loss函数的反向传播计算中存在除0或者log(0)造成的梯度变为nan和inf？

**Comment by uestcMeng** [comment]
I have encountered the same error, is there any solution to this error?
