### ISSUE TITLE
关于rsd loss中svd计算的bug

### ISSUE THREAD

**Issue by jiusigua** [thuml/Domain-Adaptation-Regression#5]
作者你好，我在使用该代码进行图像回归任务解决域适应问题时遇到一个bug；就是代码训练二十多个epoch后就开始出现提醒：
`Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.`
然后再几个epoch后就报错：
`Traceback (most recent call last):
  File "train_rsd.py", line 134, in <module>
    rsd_loss = rsd_f(feature_s, feature_t)
  File "/home/digisky/anaconda3/envs/torch1.2/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/digisky/ztj/DAR_obj/rsd.py", line 27, in forward
    U_s, _, _ = torch.svd(f_s.t())
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 14)`
我也在网上找了相关解决办法，但是都没有成功。然后我发现是在某个epoch后，梯度中出现了nan和inf，所以导致更新的权重也变为了nan，网络正向计算得到的特征中也就全部变为nan，传入到rsd loss中，svd计算就报上述的错误。请问作者有遇到过这类问题吗？有什么思路或者解决的建议吗？
谢谢！

**Comment by siaoliu** [comment]
我也出现了类似的问题，

sinpa = torch.sqrt(1-torch.pow(cospa,2))

梯度应该是由于torch.sqrt()中出现了负数导致梯度传播失败
根据这个代码，我觉得应该是压缩（1）和（torch.pow(cospa,2)）的距离，尝试使用mse直接解？
个人猜测，代码确实不大好用

**Comment by YixuanZheng-philips** [comment]
> 我也出现了类似的问题，
> 
> sinpa = torch.sqrt(1-torch.pow(cospa,2))
> 
> 梯度应该是由于torch.sqrt()中出现了负数导致梯度传播失败 根据这个代码，我觉得应该是压缩（1）和（torch.pow(cospa,2)）的距离，尝试使用mse直接解？ 个人猜测，代码确实不大好用

Same problem occured to me. Any solutions?
